### ISSUE TITLE
Large download

### ISSUE THREAD

**Issue by keypey** [r10s/messenger-android#44] opened 2017-02-13 16:41 UTC
Hi!
Please take a look at this screenshot:
![data-800mb-gsm-transfer](https://cloud.githubusercontent.com/assets/3405185/22892585/66f57e46-f213-11e6-9f79-e64b23840adc.jpg)

During three hours. I not send / receive any data! Delta Chat was not used at that time! What data and to whom they were sent?

--
keypey

**Comment by r10s** [comment] 2017-02-13 17:08
I don't know _why_ Delta Chat downloaded the data, we will check this and we already saw a similar effect (hello, Tobi ...)

But I can answer the other questions:
1. this issue only seems to happen with _some_ e-mail providers
2. I think, the app has _downloaded_ old e-mail data, I cannot imagine the app to _send_ data without request
3. Delta Chat only communicates with your  E-Mail-server; this should answer where the data come from. There is no code that communicates with other servers.

Regarding point 2: Can you verify this? Are there lots of old mails in the Inbox? Can you check the number of total mails at "Settings / About Delta Chat"?

**Comment by keypey** [comment] 2017-02-13 17:30
1. uninstalled Delta chat. I checked: Delta downloaded from yesterday 8 GB of data (wifi) and 800MB / GSM.
2. Account: google.
3. Checked account: Fact. 8.22GB of data on this account.

I understand what and why Delta downloaded.
I installed again.
Thanks.
Another q:Please take a look at this screenshot:
![pdf-file-transfer](https://cloud.githubusercontent.com/assets/3405185/22894681/330a2f94-f21a-11e6-9b90-0971dba9bd23.jpg)

When I sent "debian.epub" file. File was sent to recipients, but with attachment name:"file.epub".
 --
kp.,

**Comment by r10s** [comment] 2017-02-13 17:39
Okay, Google. This is a good hint, we will check this issue. Thank you very much.

Regarding the "Unsupported message type", see issue #13

**Comment by keypey** [comment] 2017-02-13 17:52
Thanks!
It's really an interesting project!

**Comment by mrprole** [comment] 2017-02-15 06:54
I have the same issue. Just  setup basic settings. Google mail account and password. Then all my internal storage dissappear.
![screenshot_2017-02-15-08-35-09](https://cloud.githubusercontent.com/assets/25525606/22963550/4f39463a-f35c-11e6-93c1-69a702059703.png)

**Comment by mrprole** [comment] 2017-02-15 08:55
By the way, App Info show data usage from 1 to 15 of February as 100Mb only.

**Comment by r10s** [comment] 2017-02-15 11:15
Thank you very much, all these information help us to fix the bug.

**Comment by r10s** [comment] 2017-02-16 14:13
Should be fixed by https://github.com/r10s/messenger-backend/commit/b711919abf371209aa1eeb16df085eec67ee3880 

If the problem is still present in the upcoming release (v0.1.19 or larger), please re-open this issue. For now, it is closed.

**Closed by r10s** 2017-02-16 14:13 UTC
Labels: bug

**Comment by lobit0** [comment] 2017-11-17 19:18
I had a similiar problem using Delta Chat v0.9.6:
I went to sleep and left mobile data on...
When I woke up, DC had consumed my data traffic for the month:
![data traffic consumption screenshot](https://user-images.githubusercontent.com/5931481/32964487-2a599368-cbb2-11e7-8475-c18ca9fa6952.png)
It could be related to #102, but I'm not sure.
I'm running LineageOS 14.1 nightly (Android 7.1.2-based) on a Galaxy S3 i9300 phone.
Thanks a lot for your work!
