### ISSUE TITLE
Move read mails away from inbox does not always work

### ISSUE THREAD

**Issue by escoand** [r10s/messenger-android#32] opened 2017-02-05 11:51 UTC
Currently the in-box is flooded with chat messages, hard to keep overview

**Comment by Mirodin** [comment] 2017-02-07 08:14
I second this, some way of "archiving" read messages would be great. Thunderbird for example does move messages to folders by year/month if one klicks the "Archive" button.

Something like this would make searching old messages outside of delta easier plus I hate a full inbox, looks like I have so much stuff to do ;)

**Comment by pschwede** [comment] 2017-02-07 17:53
#FYI https://support.mozilla.org/en-US/kb/organize-your-messages-using-filters

**Comment by Mirodin** [comment] 2017-02-07 18:05
I know that and that is what I am doing for my "normal" mail account, but since I use a seperate address for delta and want to access it from time to time via the webinterface I have no autofilter running.

I thought about this and came to the idea that an even better approach would be that delta creates a folder for itself and moves all new messages of one contact in respective subfolders named i.e. after the contacts address. So if I chat with john@doe.com delta would move all messages with him to DELTA/john@doe.com and messages to sally@doe.com to DELTA/sally@doe.com. I am not sure what schema we could use for groups but I am sure, if you like it we could figure out a feasible solution.

What do you guys think about this approach? It would separate messages from different contacts and make search within one "thread" easier.

**Comment by r10s** [comment] 2017-02-07 18:58
I'm not sure if subfolders as `DELTA/john@doe.com` are really useful, however, for the moment, we've other priorities at all. 

Regarding the INBOX at all: Well it is not really meant as a replacement for the "normal" E-Mail-client but more as a method to create an initial link between two persons sending the first mail to each other:

- If A sends a message to B and B does not know A, the message is not shown in any chat - only in the INBOX
- so B should hit "reply" on the message in the INBOX - and now the link is established.

That's what the INBOX was _initially_ for. Although I see, it may be useful for other puporses :-)

**Comment by escoand** [comment] 2017-02-07 19:17
My first test was with my default email mailbox so I've mixed content in the inbox.
I think our friends and families with less IT knowledge are sometimes already overcharged with one mailbox.
The solution with filters only works with a desktop client but in the most cases I read my mails with my android phone.

**Comment by r10s** [comment] 2017-02-15 11:34
> Currently the in-box is flooded with chat messages, hard to keep overview

To the original question: To clearify: Delta Chat does exactly this for all email addresses but Gmail:

In coming and outgoing messages are moved to a "Chats" folder that is created by Delta Chat.

(for Gmails-non-folder-IMAP-structure this seems a little more tricky, so we just skipped it for the moment there)

**Comment by escoand** [comment] 2017-02-15 14:07
Do I need to create this directory by hand?

**Comment by r10s** [comment] 2017-02-15 14:08
> Do I need to create this directory by hand?

No, this _should_ happen automatically.

**Comment by escoand** [comment] 2017-02-15 14:08
No, not for me.

**Comment by r10s** [comment] 2017-02-15 14:13
Which provider do you use?

**Comment by escoand** [comment] 2017-02-15 14:38
I use a self hosted mail server with Postfix and Dovecot.

**Comment by rizzopablo** [comment] 2017-02-15 20:16
I use my own Dovecot+Postfix server. 

The Chats folder could be configurable too. And Delta may verify if the default ("Chats") already exists and use it.

**Comment by r10s** [comment] 2017-02-15 21:32
Fixed with commit https://github.com/r10s/messenger-backend/commit/46106e036c689086162f4f2b49eba14b8380e787 ,  see also issue #28  

If the problem is still present in the upcoming release (v0.1.19 or larger), please re-open this issue. For now, it is closed.

**Closed by r10s** 2017-02-15 21:32 UTC
Labels: bug

**Comment by escoand** [comment] 2017-02-16 17:03
I created the chat folder by hand but Delta still not moves the messages

**Comment by r10s** [comment] 2017-02-16 17:07
v0.1.19 or larger should do the job, it will be available in F-Droid in about 24-48 hours (or have you used a self-compiled v0.1.19?)

**Comment by escoand** [comment] 2017-02-16 17:38
No, just looked at your referenced commit an found only something concerning folder creation.

**Comment by escoand** [comment] 2017-02-16 17:39
Ok, I will wait for the update and try it again.

**Comment by escoand** [comment] 2017-02-20 21:10
No, it's still not working.

**Comment by r10s** [comment] 2017-02-20 21:23
Have you tried a fresh installation?
